const oxford = [
    {id:	1282	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Divergent", authorName: "Veronica Roth", dateAdded: 	"11/11/2021", checkedOut: false,},
{id:	1283	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Insurgent", authorName: "Veronica Roth", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1284	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Allegiant", authorName: "Veronica Roth", dateAdded: 	"11/11/2021", checkedOut: false,},
{id:	1285	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "The Anthropocene Reviewed", authorName: "John Green", dateAdded: 	"11/11/2021", checkedOut: true,},
{id:	1286	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "The Other Black Girl", authorName: "Zakiya Dalila Harris", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1287	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Gone Girl", authorName: "Gillian Flynn", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1288	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Dead Simple", authorName: "Peter James", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1289	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "The Wrong Mother", authorName: "Sophie Hannah", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1290	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "The Hill We Climb: An Inaurgural Poem for the Country", authorName: "Amanda Gorman", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1291	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Evelyn The Mermicorn Fairy", authorName: "Daisy Meadows", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1292	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "You Want Women to Vote, Lizzie Stanton?", authorName: "Jean Fritz", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1293	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Bad Hair Day", authorName: "Sarah Mlynowski", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1294	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Harry Potter and the Prisoner of Azkaban", authorName: "J.K. Rowling", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1295	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Harry Potter and the Half-Blood Prince", authorName: "J.K. Rowling", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1296	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "The Young Elites", authorName: "Marie Lu", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1297	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "The Chimney Sweepers Come to Dust", authorName: "Alan Bradley", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1298	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Shanghai Girls", authorName: "Lisa See", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1299	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "The Girl Who Loved Tom Gordon", authorName: "Stephen King", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1300	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Cell", authorName: "Stephen King", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1301	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "The Front", authorName: "Patricia Cornwell", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1302	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "The Last Thing He Told Me", authorName: "Laurie Decker", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1303	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "The 9 Steps to Financial Freedom", authorName: "Suze Orman", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1304	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "I'll Walk Alone", authorName: "Mary Higgins Clark", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1305	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "The Myth of the Andalusian Paradise", authorName: "Dario Fernandez-Morera", dateAdded: "11/11/2021", checkedOut: false,},
{id:	1306	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Elmo Says...", authorName: "Sarah Albee", dateAdded: "11/12/2021", checkedOut: false,},
{id:	1307	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Doggie", authorName: "Sandra Boyton", dateAdded: "11/13/2021", checkedOut: false,},
{id:	1308	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Tending Dandelions", authorName: "Sandra Swenson", dateAdded: "11/13/2021", checkedOut: false,},
{id:	1309	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "How to Be an AntiRacist", authorName: "Ibram X. Kendi", dateAdded: "11/13/2021", checkedOut: false,},
{id:	1310	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Black Sun", authorName: "Rebecca Roanhorse", dateAdded: "11/17/2021", checkedOut: false,},
{id:	1311	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Me and Earl and the Dying Girl", authorName: "Jesse Andrews", dateAdded: "11/18/2021", checkedOut: false,},
{id:	1312	,  locationId: 	121	, address: 	"The Liddell Oxford Library", bookTitle: "Nudge", authorName: "Richard H. Thaler", dateAdded: "11/18/2021", checkedOut: false,},
{id: 1313, locationId: 121, address: "The Liddell Oxford Library", bookTitle: "Life Goals", authorName: "", dateAdded: "11/18/2021", checkedOut: false,},
{id: 1314, locationId: 121, address: "The Liddell Oxford Library", bookTitle: "David Smells!", authorName: "David Shannon", dateAdded: "11/19/2021", checkedOut: false,},
{id: 1314, locationId: 121, address: "The Liddell Oxford Library", bookTitle: "Keeping My City Weird", authorName: "Mary E. Elizabeth", dateAdded: "11/20/2021", checkedOut: false,},
{id: 1315, locationId: 121, address: "The Liddell Oxford Library", bookTitle: "Make a Trade, Charlie Brown!", authorName: "Charles M. Schulz", dateAdded: "11/20/2021", checkedOut: false,},
{id: 1316, locationId: 121, address: "The Liddell Oxford Library", bookTitle: "Mickey's Slumber Party", authorName: "Unknown", dateAdded: "11/20/2021", checkedOut: false,}]